title: Mainst Construcción

url: http://mainstconstruccion.com

markdown: kramdown

include:
- _pages

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-gallery-generator
- bourbon
- neat
